<template>
    <button>自定义按钮</button>
</template>
<style>
    button{
        width:100px;
        height:30px;
        background-color:#f00;
        color:#fff;
        outline:none;
        border:0;
    }
</style>