

const HEAD_SHOW_SUCCESS='HEAD_SHOW_SUCCESS';
const HEAD_SHOW_FAIL='HEAD_SHOW_FAIL';
const FOOTER_SHOW='FOOTER_SHOW';
const FOOTER_HIDE='FOOTER_HIDE';
export default{
	HEAD_SHOW_SUCCESS,
	HEAD_SHOW_FAIL,
	FOOTER_SHOW,
	FOOTER_HIDE
}